dist: trusty
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - node
jobs:
  fast_finish: true
before_install:
  - npm install -g yarn --cache-min 999999999
install:
- yarn
script:
- yarn index
- yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  on:
    branch: master
  github-token: $GITHUB_TOKEN
  fqdn: beta.nia.ac.cn
