<template>
  <div class="mb-2 row no-gutters">
    <b-button
      href="https://net.nia.ac.cn"
      size="lg"
      class="col-6"
      squared
      variant="outline-danger"
      >内部网络</b-button
    >
    <b-button
      href="https://github.com/UESTC-Ingress"
      size="lg"
      class="col-6"
      squared
      variant="outline-danger"
      >项目列表</b-button
    >
    <b-button
      size="lg"
      href="https://missions.nia.ac.cn"
      class="col-6"
      squared
      variant="outline-danger"
      >任务指引</b-button
    >
    <b-button
      size="lg"
      href="https://recruit.nia.ac.cn"
      class="col-6"
      squared
      variant="outline-danger"
      >招聘信息</b-button
    >
    <b-button
      size="lg"
      href="https://status.nia.ac.cn"
      class="col-6"
      squared
      variant="outline-danger"
      >设施监控</b-button
    >
    <b-button
      size="lg"
      href="http://mail.nia.ac.cn"
      class="col-6"
      squared
      variant="outline-danger"
      >邮件系统</b-button
    >
  </div>
</template>
